create table DIFF_TYPE_CONFIG(
    diff_type_id number NOT NULL PRIMARY KEY,
    diff_type varchar2(20) NOT NULL
);

insert into DIFF_TYPE_CONFIG values(1,'acme-git');
insert into DIFF_TYPE_CONFIG values(2,'acme-git-hybrid');
insert into DIFF_TYPE_CONFIG values(3,'git');
insert into DIFF_TYPE_CONFIG values(4,'svn');
insert into DIFF_TYPE_CONFIG values(5,'cc tools');
insert into DIFF_TYPE_CONFIG values(6,'clearcase');
insert into DIFF_TYPE_CONFIG values(7,'cvs');

select * from DIFF_TYPE_CONFIG;

drop table python_diff_collection;

create table PYTHON_DIFF_COLLECTION(
   diff_collection_number number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,   
   review_id number NOT NULL,
   version_no number DEFAULT 0,
   date_time DATE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'PST' NOT NULL,
   diff_type number,
   diff_source varchar2(30),
   host_name varchar2(256),
   workspace varchar2(256),
   options varchar2(50),
   review_owner varchar2(100),
   diff_server_location varchar2(2000),
   validation_time number,
   validation_status varchar2(1) DEFAULT 'N',
   diff_collection_status varchar2(1) DEFAULT 'N',
   diff_collection_msg varchar2(2000),
   diff_collection_time number,
   checksum varchar2(256),
   diff_filer_location varchar2(256),
   same_version_flag varchar2(1) DEFAULT 'N',
   process_time number,
   admin_flag varchar2(1) DEFAULT 'V',
   admin_comment varchar2(100)
 );
 
ALTER TABLE python_diff_collection ADD( trnx_id number );
ALTER TABLE python_diff_collection ADD(trnx_status varchar2(1));

-- STATUS
-- S Success    
-- F Failure
-- N Not Started
-- P Pending

create index review_id_i on python_diff_collection ( review_id );

delete from python_diff_process;
delete from python_diff_collection;

select * from python_diff_collection order by diff_collection_number;
select * from python_diff_process order by diff_collection_number;
select * from python_diff_detail order by diff_collection_number;

insert into python_diff_collection(review_id,host_name,workspace,options) values(9010102,'sjc-ads-981','/nobackup/ashish/den/','/-C -p');

UPDATE python_diff_collection SET validation_time=4.1,validation_status='S' where diff_collection_number=27;
select diff_collection_number from python_diff_collection where review_id=9010102 and version_no=0;
   
create table PYTHON_DIFF_PROCESS(
   diff_process_number number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
   diff_collection_number number NOT NULL,
   review_id number NOT NULL,
   parsing_status varchar2(1) DEFAULT 'N',
   parsing_msg varchar2(2000),
   parsing_time number,
   sbs_status varchar2(1) DEFAULT 'N',
   sbs_msg varchar2(2000),
   sbs_time number,
   mapping_status varchar2(1) DEFAULT 'N',
   mapping_msg varchar2(2000),
   mapping_time number,
   process_time number,
   process_status varchar2(1) DEFAULT 'N',
   admin_flag varchar2(1) DEFAULT 'V',
   admin_comment varchar2(100),
   constraint diff_fk foreign key(diff_collection_number) references python_diff_collection(diff_collection_number)
);

create index review_id_p on python_diff_process ( review_id );

create table PYTHON_DIFF_DETAIL(
    diff_detail_number number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY, 
    diff_process_number number NOT NULL,
    diff_collection_number number NOT NULL,
    review_id number,
    version_no number,
    file_details clob,
    file_mappings clob,
    number_of_component number,
    number_of_file number,
    comp_list clob,
    file_list clob,
    lines_added number,
    diff_comp_detail clob,
    admin_flag varchar2(1) DEFAULT 'V',
    constraint diff_job_fk foreign key(diff_collection_number) references python_diff_collection(diff_collection_number),
    constraint process_fk foreign key(diff_process_number) references python_diff_process(diff_process_number)
);

create index review_id_d on python_diff_detail ( review_id );
   desc prrq_queue_review;
   select count(review_id),review_priority_id from prrq_queue_review group by review_priority_id;
   select * from prrq_review_diff_extracted where review_id=3012154;
   
   select * from prrq_review_diff_detail where diff_type = 'git_diff' order by review_id desc;